baseURL = 'http://blueeon.github.io/'
languageCode = 'en-us'
title = 'blueeon 的日志'
theme = "tale-hugo"
contentdir = "content"
publishdir = "public"
disableSitemap=false
disableRSS=false
[params]
  description = "文以载道"
  author = "blueeon"