baseURL = 'http://blueeon.github.io/'
languageCode = 'en-us'
title = 'blueeon 的日志'
theme = "PaperMod"
paginate = 5

contentdir = "content"

publishdir = "docs"
disableSitemap=false
disableRSS=false
staticdir="static"
[Author]
    name="blueeon"

[params]
  description = "文以载道"
  author = "blueeon"